# Generated by Django 5.1.1 on 2024-09-30 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_cartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="added_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
