# Generated by Django 5.1.1 on 2024-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
