# Generated by Django 5.1.1 on 2024-10-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_order_status_delete_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                ],
                default="Choose payment method",
                max_length=20,
            ),
        ),
    ]
