# Generated by Django 5.1.1 on 2024-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                ],
                default="razorpay",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
