# Generated by Django 5.1.1 on 2025-01-06 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_order_payment_method_alter_userprofile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="created_at",
        ),
    ]
