# Generated by Django 5.1.1 on 2025-01-06 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_order_date_order_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
    ]
