# Generated by Django 5.1.1 on 2025-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("razorpay", "Razorpay")],
                max_length=20,
            ),
        ),
    ]
